config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :posts do 
    resources :comments
  end
 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :projects do 
    resources :attachers
    resources :tasks
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  root 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET projects/1/tasks
  def index
    @tasks = @project.tasks
  end

  # GET projects/1/tasks/1
  def show
      
  end

  # GET projects/1/tasks/new
  def new
    @task = @project.tasks.build
    @tasks = @project.tasks
  end

  # GET projects/1/tasks/1/edit
  def edit
  end

  # POST projects/1/tasks
  def create
    @task = @project.tasks.build(task_params)

    if @task.save
      redirect_to new_project_task_path
    else
      render action: 'new'
    end
  end

  # PUT projects/1/tasks/1
  def update
    if @task.update(task_params)
      redirect_to new_project_task_path
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/tasks/1
  def destroy
      @task.destroy
          redirect_to new_project_task_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:project_id])
    end

    def set_task
      @task = @project.tasks.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:description)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="div_edit_task">
<%= form_for([@task.project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field"><br />
    <%= f.label :description  %><br />
    <%= f.text_area :description, class: "form-control"%>
  </div><br />
  <div class="actions">
    <%= f.submit "Edit", class: "btn btn-primary"%>
  </div><br />
<% end %>
</div>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= task.project_id %>
  </p>

</div>

app/views/tasks/edit.html.erb
<nav class="navbar navbar-expand-lg  bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><h4>Hello<%= current_user.email %></h4></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-md-auto gap-2">
        <li class="nav-item rounded">
          <a class="nav-link active" aria-current="page" href="/"><i class="bi bi-house-fill me-2"></i>Home</a>
        </li>

        <li class="nav-item rounded">
         <%= link_to new_project_task_path, class: "nav-link" do %>
            <i class="bi bi-clipboard2-plus-fill"></i> Home Task
          <% end %>
        </li>
       
      </ul>
    </div>
  </div>
</nav><br />

<h1 align=center>Editing task</h1>
<div class="container border">
  <%= render "form", task: @task %>
</div>

<style>
.nav-item{
  background-color: white
}
.navbar-nav .nav-item:hover {
  background-color: white;
}
.navbar-brand{
  color: white
}

</style>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", task %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
<nav class="navbar navbar-expand-lg  bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><h4>Hello<%= current_user.email %></h4></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-md-auto gap-2">
        <li class="nav-item rounded">
          <a class="nav-link active" aria-current="page" href="/"><i class="bi bi-house-fill me-2"></i>Home</a>
        </li>

        <li class="nav-item rounded">
         <%= link_to projects_path, class: "nav-link" do %>
            <i class="bi bi-clipboard2-plus-fill"></i> Home Projects
          <% end %>
        </li>
       
      </ul>
    </div>
  </div>
</nav><br />


<%= form_for([@task.project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
      <div class="container">
          <div class="container border">
              <div class="container">
                <h4 align="center">To Do App</h4>
                  <label class="form-label" for="form1">Enter a task here</label><br />
                  <div class="input-group mb-3">   
                    <%= f.text_area :description, class: "form-control"  %>
                  </div>
                  <%= f.submit "Creat Task", class:"btn btn-primary"%>
              </div><br />
            </div>
      </div>
            
      <% end %>
    
<div class="container table-responsive py-5"> 
  <table class="table table-bordered table-hover">
    <thead class="text-white bg-dark">
      <tr>
        <th scope="col">id</th>
        <th scope="col">Description</th>
        <th scope="col">Actions</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>  
        <% @tasks.each do |task| %>
        <% if task.persisted? %>
      <tr>
        <th scope="row"><%= task.id %></th>
        <td><%= task.description %></td>
        <td><%= link_to 'Edit', edit_project_task_path(task.project, task), class: "btn btn-success ms-1"  %></td>
        <td><%= button_to 'Destroy', [task.project, task], method: :delete, class:"btn btn-danger" %></td>
      </tr>  
        <% end %>
        <% end %>
    </tbody>
  </table>
</div>

<style>
.nav-item{
  background-color: white
}
.navbar-nav .nav-item:hover {
  background-color: white;
}
.navbar-brand{
  color: white
}

</style>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>