config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :posts do 
    resources :comments
  end
 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :projects do 
    resources :attachers
    resources :tasks
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  root 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/attacher.rb
class Attacher < ApplicationRecord
  belongs_to :project
  has_one_attached :uploader
  # mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
   validates :name, presence: true
end

app/controllers/attachers_controller.rb
class AttachersController < ApplicationController
  before_action :set_project
  before_action :set_attacher, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /attachers or /attachers.json
  def index
    @attachers = @project.attacher

  end

  # GET /attachers/1 or /attachers/1.json
  def show
  end

  # GET /attachers/new
  def new
    @attacher = @project.attacher.new
  end

  # GET /attachers/1/edit
  def edit
  end

  # POST /attachers or /attachers.json
  def create
    @attacher = @project.attacher.build(attacher_params)

    if @attacher.save
      redirect_to project_attachers_path
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /attachers/1 or /attachers/1.json
  def update
    
      if @attacher.update(attacher_params)
        redirect_to(@attacher.project)
      else
        render actions: 'edit'
      end
    
  end

  # DELETE /attachers/1 or /attachers/1.json
  def destroy
    @attacher.destroy 
    redirect_to project_attachers_path
  end

  private

  def set_project
    @project = current_user.projects.find(params[:project_id])
  end


    # Use callbacks to share common setup or constraints between actions.
    def set_attacher
      @attacher = @project.attacher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attacher_params
      params.require(:attacher).permit(:name, :uploader, :project_id)
    end
end

app/helpers/attachers_helper.rb
module AttachersHelper
end

app/views/attachers/_attacher.html.erb
<div id="<%= dom_id attacher %>">
  <p>
    <strong>Name:</strong>
    <%= attacher.name %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= attacher.project_id %>
  </p>

</div>

app/views/attachers/_form.html.erb
<%= form_for([@attacher.project, @attacher]) do |form| %>
  <% if @attacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attacher.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @attacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="mb-2">
          <label for="exampleFormControlInput1" class="form-label">Name</label>
          <%= form.text_field :name, class: "form-control", id: "exampleFormControlInput1", placeholder: "Name" %>
      </div>

    <div class="mb-3">
      <label for="formFileDisabled" class="form-label">Disabled file input example</label>
      <%= form.file_field :uploader, class: "form-control", id: "formFileDisabled" %>

    </div>
     <%= form.submit "Add", class: "btn btn-outline-primary" %> 
</div>
 

   
       
<% end %>

app/views/attachers/edit.html.erb
<h1>Editing attacher</h1>

<%= render "form", attacher: @attacher %>

<br>

<div>
  <%= link_to "Show this attacher", @attacher %> |
  <%= link_to "Back to attachers", attachers_path %>
</div>

app/views/attachers/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-md-auto gap-2">
        <li class="nav-item rounded">
          <a class="nav-link active" aria-current="page" href="/"><i class="bi bi-house-fill me-2"></i>Home</a>
        </li>

        <li class="nav-item rounded">
         <%= link_to projects_path, class: "nav-link" do %>
            <i class="bi bi-clipboard2-plus-fill"></i> Home Projects
          <% end %>
        </li>

         <li class="nav-item rounded">
         <%= link_to new_project_attacher_path, class: "nav-link" do %>
            <i class="bi bi-file-earmark-plus"></i> New attachments
          <% end %>
        </li>
       
      </ul>
    </div>
  </div>
</nav>
<br />


<h1 align="center">Attachers</h1>
<br />

<div class="container">
  <table class="table table-dark">

    <thead> 
    
      <tr>
        <th scope="col">id</th>
        <th scope="col">Name</th>
        <th scope="col">File</th>
        <th scope="col">Handle</th>
      </tr>
    </thead>
    <tbody>
    <% @attachers.each do |attacher| %> 
      <tr>
        <th scope="row"> <%= attacher.id %></th>
          <td><%= attacher.name %></td>
          <td>  <% if attacher.uploader.attached? %>
                  <% if  attacher.uploader.image?%>
                    <%= link_to image_tag(attacher.uploader, class: "img_upload"),  rails_blob_path(attacher.uploader, disposition: "attachment") %>
                    <% elsif attacher.uploader.audio? %>
                        <%= rails_blob_url(attacher.uploader, disposition: "attachment") %>
                      <% else %>
                          <%= link_to attacher.uploader.filename,  rails_blob_path(attacher.uploader, disposition: "attachment") %>
                    <% end %>
          <% end %></td>
         
        <td> <%= button_to 'Destroy', [attacher.project, attacher], method: :delete, class: "btn btn-danger"  %>
        </td>
      </tr> <% end %>
    </tbody>

  </table>

</div>

 



<style>

.img_upload{
   border: 1px solid #ddd;
  border-radius: 4px;
  padding: 5px;
  width: 150px;
}
body {
  font-family: Montserrat, sans-serif;
}
.navbar-brand {
  background-position: center;
  background-repeat: no-repeat;
  background-size: contain;
  width: 48px;
  height: 48px;
}

.navbar-nav .nav-item:hover {
  background-color: rgba(180, 190, 203, 0.4);
}


</style>

app/views/attachers/new.html.erb
<nav class="navbar navbar-expand-lg  bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><h4>Hello<%= current_user.email %></h4></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-md-auto gap-2">
        <li class="nav-item rounded">
          <a class="nav-link active" aria-current="page" href="/"><i class="bi bi-house-fill me-2"></i>Home</a>
        </li>
         <li class="nav-item rounded">
         <%= link_to project_attachers_path, class: "nav-link" do %>
            <i class="bi bi-file-earmark-plus"></i> Attachments Home
          <% end %>
        </li>
       
      </ul>
    </div>
  </div>
</nav><br />

<h1 align="center">New attacher</h1>
<div class="container">
  <div class="border">
    <%= render "form", attacher: @attacher %>
  </div>
</div>
<style>
.nav-item{
  background-color: white
}
.navbar-nav .nav-item:hover {
  background-color: white;
}
.navbar-brand{
  color: white
}

</style>