config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :posts do 
    resources :comments
  end
 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :projects do 
    resources :attachers
    resources :tasks
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  root 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  has_many :attacher, dependent: :destroy
  has_many :tasks, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json

 
  def index
    @projects = Project.all
    @attacher = Attacher.find_by(params[:project_id])
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = current_user.projects.new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.create(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to root_path, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :discription, :user_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="container">
    <div class="mb-2">
        <label for="exampleFormControlInput1" class="form-label">Name</label>
        <%= form.text_field :name, class: "form-control",id: "exampleFormControlInput1", placeholder: "Name"  %>
    </div>
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Discription</label>
        <%= form.text_area :discription, class: "form-control", id: "exampleFormControlTextarea1",rows: "3", placeholder: "Discription"    %>
      </div>
      <div>
        <%= form.number_field :user_id, id: :project_user_id, value: current_user.id, type: :hidden %>
      </div>

        <div>
          <%= form.submit "Create Project", class: "btn btn-outline-success"  %>
        </div>
  </div>
   
</div>





<% end %>

<style>

</style>

app/views/projects/_navbar.html.erb
<nav class="navbar navbar-expand-lg  bg-primary">
  <div class="container-fluid">

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-md-auto gap-2">
        <li class="nav-item rounded">
          <a class="nav-link active" aria-current="page" href="/"><i class="bi bi-house-fill me-2"></i>Home</a>
        </li>

        <li class="nav-item rounded">
         <%= link_to new_project_path, class: "nav-link" do %>
            <i class="bi bi-clipboard2-plus-fill"></i> New Projects
          <% end %>
        </li>
        <li class="nav-item dropdown rounded">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-person-fill me-2"></i>Profile</a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Account</a></li>
            <li><%= link_to edit_user_registration_path, class: "dropdown-item" do %>  
                Edit
              <% end %></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><%= button_to  destroy_user_session_path, method: :delete, class: "dropdown-item" do %> 
              Logout 
            <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>


<style>
body {
  font-family: Montserrat, sans-serif;
}

.nav-item{
  background-color: white
}
.navbar-nav .nav-item:hover {
  background-color: white;
}


</style>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<%= render 'projects/navbar' %>
<section class="page-contain">

     <% @projects.each do |project| %>
          <% if project.user_id == current_user.id %>
          <%= link_to  project, class: "data-card" do %>
              
               <h3><%= project.name %></h3>
               <h4><%= project.discription %> </h4>
               <span class="link-text">
                    View All Project

                    <path fill-rule="evenodd" clip-rule="evenodd" d="M17.8631 0.929124L24.2271 7.29308C24.6176 7.68361 24.6176 8.31677 24.2271 8.7073L17.8631 15.0713C17.4726 15.4618 16.8394 15.4618 16.4489 15.0713C16.0584 14.6807 16.0584 14.0476 16.4489 13.657L21.1058 9.00019H0.47998V7.00019H21.1058L16.4489 2.34334C16.0584 1.95281 16.0584 1.31965 16.4489 0.929124C16.8394 0.538599 17.4726 0.538599 17.8631 0.929124Z" fill="#753BBD"/>
                    </svg>
               </span>
           </a> 
          
          <% end %>
          
          <% end %>
<% end %>
</section>






<style>
@import url("https://fonts.googleapis.com/css2?family=Open+Sans:wght@600;700&display=swap");
* {
  box-sizing: border-box;
}

.page-contain {
  display: flex;
  min-height: 100vh;
  align-items: center;
  justify-content: center;
  padding: 2em;
}

.data-card {
  border-radius: 10px;
  background-color: aqua;
  color: black;
  display: flex;
  flex-direction: column;
  text-decoration: none;
  margin: 1em;
  padding: 2.75em 2.5em;
}
.data-card h3 {
  font-size: 3.5em;
  font-weight: 600;
}
.data-card .link-text {
  font-size: 1.125em;
}

</style>

app/views/projects/new.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-md-auto gap-2">
        <li class="nav-item rounded">
          <a class="nav-link active" aria-current="page" href="/"><i class="bi bi-house-fill me-2"></i>Home</a>
        </li>

        <li class="nav-item rounded">
         <%= link_to projects_path, class: "nav-link" do %>
            <i class="bi bi-clipboard2-plus-fill"></i> Projects
          <% end %>
          
        </li>
        <li class="nav-item dropdown rounded">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-person-fill me-2"></i>Profile</a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Account</a></li>
            <li><%= link_to edit_user_registration_path, class: "dropdown-item" do %>  
                Edit
              <% end %></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><%= button_to  destroy_user_session_path, method: :delete, class: "dropdown-item" do %> 
              Logout 
            <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav><br />

<h1 align="center">New project</h1>

<%= render "form", project: @project %>

app/views/projects/show.html.erb
<nav class="navbar navbar-expand-lg bg-primary">
  <div class="container-fluid">

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-md-auto gap-2">
        <li class="nav-item rounded">
          <a class="nav-link active" aria-current="page" href="/"><i class="bi bi-house-fill me-2"></i>Home</a>
        </li>

        <li class="nav-item rounded">
         <%= link_to projects_path, class: "nav-link" do %>
            <i class="bi bi-clipboard2-plus-fill"></i> Home Projects
          <% end %>
          
        </li>
        <li class="nav-item dropdown rounded">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-person-fill me-2"></i>Projects</a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Account</a></li>
            <li><%= link_to edit_project_path(@project), class: "dropdown-item" do %>  
                Edit Projects
              <% end %></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><%= button_to @project, method: :delete, class: "dropdown-item" do %> 
              Delete Project 
            <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
<br />


<h1 align="center"><%= @project.name %></h1><br />

<div class="qw">
  <div class="card1">
    <h1 >Attachment</h1>
    <div class="container">
      <h4><%= link_to "Attachers", project_attachers_path(@project), class: 'a_task_att' %></h4> <br />
    </div>
  </div>

  <div class="card2">
    <h1>Task</h1>
      <div class="container">
      <h4><%= link_to "Tasks", new_project_task_path(@project), class: 'a_task_att' %></h4> 
      </div>
  </div>
</div>





<style>
.nav-item{
  background-color: white
}
.navbar-nav .nav-item:hover {
  background-color: white;
}

.card1 {
  position: absolute;
  right: 50%;
    text-align: center;
    width: 27%;
    # border: 1px solid black;
    height:  200px; 
    border-radius: 10px;   
    color: black;
    background-color: aqua;
    box-shadow: 5px 10px  black;
}
.card2 {
  position: absolute;
  right: 20%;
    /* justify-self: center; */
    text-align: center;
    width: 27%;
    height:  200px; 
    border-radius: 10px;    
    # color: #ef959a;
    # background-color: #212529;
    color: black;
    background-color: aqua;
    box-shadow: 5px 10px  black;
}

</style>